# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=128, null=True, verbose_name='Failo vardas')),
            ],
            options={
                'verbose_name': 'Paveiksliukas',
                'verbose_name_plural': 'Paveikslėlis',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Pavadinimas')),
                ('x', models.FloatField(blank=True, null=True, verbose_name='X koordinatė')),
                ('y', models.FloatField(blank=True, null=True, verbose_name='Y koordinatė')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Adresas')),
            ],
            options={
                'verbose_name': 'Vietovė',
                'verbose_name_plural': 'Vietovės',
            },
        ),
        migrations.CreateModel(
            name='TourObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Pavadinimas')),
                ('ticket_price', models.FloatField(verbose_name='Bilieto kaina')),
                ('last_update', models.DateTimeField(verbose_name='Paskutinis atnaujinimas')),
                ('link', models.CharField(max_length=128, verbose_name='Oficialus puslapis')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Papildoma informacija')),
            ],
            options={
                'verbose_name': 'Turistinis objektas',
                'verbose_name_plural': 'Turistiniai objektai',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('tour_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_tourist.TourObject')),
                ('event_date', models.DateTimeField(verbose_name='Renginio data')),
                ('event_end_date', models.DateTimeField(verbose_name='Renginio pabaiga')),
                ('is_concert', models.BooleanField(default=False, verbose_name='Koncertas')),
                ('is_festival', models.BooleanField(default=False, verbose_name='Masinė kultūros šventė')),
                ('is_exhibition', models.BooleanField(default=False, verbose_name='Paroda')),
            ],
            options={
                'verbose_name': 'Renginys',
                'verbose_name_plural': 'Renginiai',
            },
        ),
        migrations.CreateModel(
            name='VisitPlace',
            fields=[
                ('tour_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_tourist.TourObject')),
                ('always_available', models.BooleanField(default=False, verbose_name='Prieinama visuomet')),
                ('mondayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Pirmadienio darbo pradžia')),
                ('mondayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Pirmadienio darbo pabaiga')),
                ('tuesdayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Antradienio darbo pradžia')),
                ('tuesdayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Antradienio darbo pabaiga')),
                ('wednesdayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Trečiadienio darbo pradžia')),
                ('wednesdayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Trečiadienio darbo pabaiga')),
                ('thursdayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Ketvirtadienio darbo pradžia')),
                ('thursdayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Ketvirtadienio darbo pabaiga')),
                ('fridayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Penktadienio darbo pradžia')),
                ('fridayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Penktadienio darbo pabaiga')),
                ('saturdayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Šeštadienio darbo pradžia')),
                ('saturdayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Šeštadienio darbo pabaiga')),
                ('sundayWorkingHoursStart', models.TimeField(blank=True, null=True, verbose_name='Sekmadienio darbo pradžia')),
                ('sundayWorkingHoursEnd', models.TimeField(blank=True, null=True, verbose_name='Sekmadienio darbo pabaiga')),
                ('is_museum', models.BooleanField(default=False, verbose_name='Muziejus')),
                ('is_park_or_square', models.BooleanField(default=False, verbose_name='Parkas / Aikštė')),
                ('is_famous_place', models.BooleanField(default=False, verbose_name='Ižymi vieta')),
                ('is_monument', models.BooleanField(default=False, verbose_name='Istorinis paminklas')),
                ('is_palace', models.BooleanField(default=False, verbose_name='Dvaras / Pilis')),
                ('is_nature_object', models.BooleanField(default=False, verbose_name='Gamtos objektas')),
            ],
            options={
                'verbose_name': 'Lankytina vieta',
                'verbose_name_plural': 'Lankytinos vietos',
            },
        ),
        migrations.AddField(
            model_name='tourobject',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tourist.Place', verbose_name='Vietovė'),
        ),
        migrations.AddField(
            model_name='image',
            name='tour_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tourist.TourObject', verbose_name='Turistinis objektas'),
        ),
    ]
