# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0003_auto_20161117_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitplace',
            name='is_famous_place',
        ),
        migrations.AddField(
            model_name='tourobject',
            name='title',
            field=models.CharField(default='a', max_length=50, verbose_name='Pavadinimas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplace',
            name='is_panorama',
            field=models.BooleanField(default=False, verbose_name='Panorama'),
        ),
    ]
