# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0005_auto_20161117_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplace',
            name='is_church',
            field=models.BooleanField(default=False, verbose_name='Istorinis paminklas'),
        ),
    ]
