# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0007_auto_20161118_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourobject',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oficialus puslapis'),
        ),
        migrations.AlterField(
            model_name='tourobject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
    ]
