# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0008_auto_20161118_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourobject',
            name='main_photo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Pagrindinė nuotrauka'),
        ),
    ]
