# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0009_tourobject_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Paveiksliukas'),
        ),
        migrations.AlterField(
            model_name='tourobject',
            name='main_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Pagrindinė nuotrauka'),
        ),
    ]
