# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tourist', '0011_auto_20161118_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('tour_object', models.ManyToManyField(to='app_tourist.TourObject', verbose_name='Objektai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Naudotojas')),
            ],
            options={
                'verbose_name': 'Maršrutas',
                'verbose_name_plural': 'Maršrutai',
            },
        ),
    ]
