# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0012_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_object',
            new_name='tour_objects',
        ),
    ]
