# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0013_auto_20161121_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='area_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kodas'),
        ),
    ]
