# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0014_place_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pašto kodas'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('title', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together=set([('title', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='tourobject',
            unique_together=set([('title', 'place')]),
        ),
    ]
