# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0015_auto_20161124_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Pavadinimas'),
        ),
    ]
