# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-12 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tourist', '0016_auto_20161201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Naudotojas'),
        ),
    ]
