# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tourist', '0015_auto_20161124_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Komentaras')),
                ('mark', models.CharField(choices=[('0', 'Nepatiko'), ('1', 'Vidutiniškai'), ('2', 'Patiko')], max_length=1, verbose_name='Įvertinimas')),
                ('date_posted', models.DateTimeField(verbose_name='Parašymo data')),
                ('tour_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tourist.TourObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Naudotojas')),
            ],
            options={
                'verbose_name_plural': 'Nuomonės',
                'verbose_name': 'Nuomonė',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('0', 'Blogai'), ('1', 'Gerai')], max_length=1, verbose_name='Balsas')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_opinions.Opinion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Naudotojas')),
            ],
            options={
                'verbose_name_plural': 'Balsai',
                'verbose_name': 'Balsas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'opinion')]),
        ),
    ]
